#
# Generated by the NeXT Project Builder.
#
# NOTE: Do NOT change this file -- Project Builder maintains it.
#
# Put all of your customizations in files called Makefile.preamble
# and Makefile.postamble (both optional), and Makefile will include them.
#

NAME = VMWareFB

PROJECTVERSION = 1.1
LANGUAGE = English

LOCAL_RESOURCES = Info.rtf Localizable.strings

GLOBAL_RESOURCES = Default.table Display.modes

TOOLS = vmwareFB_reloc.tproj

OTHERSRCS = Makefile Makefile.postamble Makefile.preamble

MAKEFILEDIR = /NextDeveloper/Makefiles/app
MAKEFILE = bundle.make
SOURCEMODE = 444

BUNDLE_EXTENSION = config
LIBS = -lIndexing_s
PROF_LIBS = -lIndexing_s




-include Makefile.preamble

include $(MAKEFILEDIR)/$(MAKEFILE)

-include Makefile.postamble

-include Makefile.dependencies
